spring.application.name=fulfilment-service
server.port=8080

# Production Database (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.hbm2ddl.import_files=
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
